version: '3.8'
services:
  productservice:
    container_name: productservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6095:6095"
      - "6085:6085"
    expose:
      - 6095
      - 6085
    volumes:
      - ./:/app/app
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://warehouse-db:5432/warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

    networks:
      - rabbitmq_nodejs
      - product_db_net

networks:
  rabbitmq_nodejs:
    name: rabbitmq_nodejs
    driver: bridge
  auth-network:
    driver: bridge
  warehouse_db_net:
    name: warehouse_db_net
    driver: bridge
  product_db_net:
    name: product_db_net
    driver: bridge




